travis:
  secure:
    BINSTAR_TOKEN: U0opXuorEJE8G3ceyFs6wtMphOrCKRe4Ew6UZEfPOZ4Dh1sjG15KFmOBWFG2ccBLLYlLL+Jo6F9Fy3TawDsF3h2Kc8Km705gUVbRo7wZGKbmjgr6Hsbpp95vKIeNl1ihfuKbm6L7KSuSaZFbL0DQ5xb3zsh6KTIEKg5gxPTVT5plxLYu7K/npxBE9kK+4XiLek7D49xpJfySz36DQ2bqm7Y1DUepkUCflfylBKsu27cJWLGmAxMfRZr56U/qwueiHsYOveJl8GatgsS7fL4r/fjbfzWJwOwVnVFhvSNVnxMtiHopMpHY7Ie72Pso/zVMsv5rnnacpVwiTY7RCc7bYSislqIDjMJM/QOLHGmT+7onGDpH/Dj9kGlSudcQEPjKPHkQCQMMau+xAvyh6/tHFhrg5sRp985ZjCjFhmKPwzYBPUa2cOi6IzWDKZ0Ct6VwJPjX50S2V6DpmFwqrYH4MCiVTTXIdkcGX66WyU9+Z649JhwoxtcLe02eS4Bea0sYbdJmBSvnaPOaJHW1/HsjQfiwOpunRLRx9LlbKzQETpta/D/SQ8+CotS9/EMkBCgJgDtxPa5CjWwOkSafIDZQ4+AxcK1BFftW5julQ7A4UlX1MvDlSpoa/J6ZycwX4bFadkts2LHFAKdRX6wxSdgZfRZa8FizQ8+zkpUljvm7tPU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
