travis:
  secure:
    BINSTAR_TOKEN: QI6hbAcBwW0XCYY6MsAiFkudl2k+XB1b1JGGScQ4kArJCwz5OL51kEIOltjGtpgon7WulrJn3E7zVsWoxS8JP+2GGpogxEwE1oiz5DWcLSqbYLon1hblOrp7RHOBfmx8FnOjnrQf5Qnd5FjDtqWvMrLuscfQ6TqqJjZy5qkzYdgXfvjMvpzHyUj+vf40hwdcp7rnpSMQgVc9JuLoKsWu1cyZBdpMqt1YrTkDbKY1wqmImZiTm3IgAMlxmQykD4LIzUwcjZu3TW4LzXk2Z5CrH+0/QXavSZ5vxr8HYrESYI60umsvow7w8kLz1mZFPsYohxKI3Si7PDofVsaA6eC1JhlNVJQYOIH/8Z7/rUAiDmdQUqGT2/Zro+kaKAM+aZ9s6VEfVerm0CAuv6veSOsBKeiWWvgKX5T5Sed53UJsZN1br7Cid4COWwMHyAeqGwqvXuuze551uk4FOz70rbTKfiV/cnea5scA4yqnq+PNDgAnwA+iCxFr5BOmGoEhvgTpt6/3W1yVUx/O3fTI353OcrEGn/LFF12PolahYlo1QLXV9Hz71bEIR/xVkPHjvyRniqYKuxy1PQr0Jk4wYqn9y8m6Q58257VUFQrnyxoJxz/ttlHpaE2FIvvIqL8HkyGZdhLBObj3olGQuoOHDuYKxKVjAHGyuSu8sKqZLYo0ddA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
